[package]
name = "blockchain"
version = "0.1.0"
authors = ["Max <max@recoset.com>"]

[dependencies]
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"

[[bin]]
name = "server"
path = "src/server.rs"
